Import('env')

env['CCFLAGS'] += ' -O0'

env['CPPPATH'] += [
    '../components/async/include'
]

env['LIBPATH'] = [
    '../src',
] + env['TARGET_LIBPATH']

env['LIBS'] = [
    'async',
] + env['TARGET_LIBS']

env.ParseConfig(env['CONFIG_PARSER'])

env.Substfile('fstracecheck.in',
              '#fstracecheck.in',
              SUBST_DICT={
                  '@CC@': env['CC'],
                  '@CPPFLAGS@':  env['_CPPDEFFLAGS'] + env['_CPPINCFLAGS'],
                  '@FSTRACECHECK@': env['FSTRACECHECK'],
              }
)
env.Command('fstracecheck',
            'fstracecheck.in',
            [
                Copy('$TARGET', '$SOURCE'),
                Chmod('$TARGET', 0o755),
            ]
)

env.Program(
    'asynctest',
    [
        'asynctest-alock.c',
        'asynctest-base64encoder.c',
        'asynctest-blobstream.c',
        'asynctest-blockingstream.c',
        'asynctest-chunkdecoder.c',
        'asynctest-chunkencoder.c',
        'asynctest-clobberstream.c',
        'asynctest-concatstream.c',
        'asynctest-drystream.c',
        'asynctest-emptystream.c',
        'asynctest-framers.c',
        'asynctest-fsadns.c',
        'asynctest-iconvstream.c',
        'asynctest-json.c',
        'asynctest-jsonserver.c',
        'asynctest-jsonthreader.c',
        'asynctest-loop-protected.c',
        'asynctest-multipart.c',
        'asynctest-nicestream.c',
        'asynctest-old-school.c',
        'asynctest-pacerstream.c',
        'asynctest-pausestream.c',
        'asynctest-poll.c',
        'asynctest-probestream.c',
        'asynctest-queuestream.c',
        'asynctest-stringstream.c',
        'asynctest-subprocess.c',
        'asynctest-tcp.c',
        'asynctest-timer.c',
        'asynctest-zerostream.c',
        'asynctest.c',
    ],
)

env.Program('timerperf',
            [ 'timerperf.c' ])
