Import('env')
import os

env.Command('async_version.c', [],
            """echo 'const char *async_version_tag = \
    "F-S_v:: async 1.0.%s";' >$TARGET""" % os.getenv("BUILD_NUMBER", "9999"))

env['CCFLAGS'] += ' -fPIC'      # make objects usable for shared libs

env['CPPPATH'] = [
    '#include',
]

env.ParseConfig(env['CONFIG_PARSER'])

env.StaticLibrary(
    'async',
    [
        'async.c',
        'async_version.c',
        'base64decoder.c',
        'base64encoder.c',
        'blobstream.c',
        'blockingstream.c',
        'bytestream_1.c',
        'chunkdecoder.c',
        'chunkencoder.c',
        'chunkframer.c',
        'clobberstream.c',
        'concatstream.c',
        'deserializer.c',
        'drystream.c',
        'emptystream.c',
        'errorstream.c',
        'farewellstream.c',
        'fsadns.c',
        'iconvstream.c',
        'json_connection.c',
        'jsondecoder.c',
        'jsonencoder.c',
        'jsonserver.c',
        'jsonyield.c',
        'multipartdecoder.c',
        'multipartdeserializer.c',
        'naivedecoder.c',
        'naiveencoder.c',
        'naiveframer.c',
        'nicestream.c',
        'notification.c',
        'pacer.c',
        'pacerstream.c',
        'pausestream.c',
        'pipestream.c',
        'probestream.c',
        'queuestream.c',
        'reservoir.c',
        'stringstream.c',
        'subprocess.c',
        'substream.c',
        'switchstream.c',
        'tcp_client.c',
        'tcp_connection.c',
        'tricklestream.c',
        'yield_1.c',
        'zerostream.c',
    ],
)
